// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    [Migration("20250916073828_BookData")]
    partial class BookData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scoot Fitxgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Title = "Moby-Dick",
                            YearPublished = 1851
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
